#CTRL+ALT+R
POST http://localhost:3001/user/register
Content-Type: application/json

{
    "email": "goodbye@email.com",
    "password": "goodbyegoodbye"
}

###

POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email": "goodbye@email.com",
    "password": "goodbyegoodbye"
}

###

GET http://localhost:3001/questions

###

POST http://localhost:3001/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGZlMTAxZTEyZWE0ZmNlY2U5ZTljMiIsImlhdCI6MTY1ODg0OTQxNywiZXhwIjoxNjU4ODUzMDE3fQ.-A5Wp0HRYCNB3726GJefhb7nrikr58fz1Dy2X2TiBOQ
Content-Type: application/json

{
"body": "For me it took a little bit less",
      "isEdited": false,
      "likes": [],
      "qid": "62dfdea4c7a4453c21d09775",
      "uid": "62dfe15ce12ea4fcece9e9c3",
      "dislikes": []
}

###

DELETE http://localhost:3001/questions/62e00b065dcb3096e9c44b36
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGZlMTAxZTEyZWE0ZmNlY2U5ZTljMiIsImlhdCI6MTY1ODg0OTQxNywiZXhwIjoxNjU4ODUzMDE3fQ.-A5Wp0HRYCNB3726GJefhb7nrikr58fz1Dy2X2TiBOQ

###

PUT http://localhost:3001/questions/62e00bb94c0b1ae77d25fd61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGZlMTAxZTEyZWE0ZmNlY2U5ZTljMiIsImlhdCI6MTY1ODg0OTQxNywiZXhwIjoxNjU4ODUzMDE3fQ.-A5Wp0HRYCNB3726GJefhb7nrikr58fz1Dy2X2TiBOQ
Content-Type: application/json

{
    "title": "Is Node difficult to learn?",
    "body": "I am starting Node jorney and I wonder if it is difficult to learn",
    "isRead": false,
    "isEdited": false,
    "uid": "62dfe15ce12ea4fcece9e9c3"   
}

###

GET http://localhost:3001/questions/62dfdea4c7a4453c21d09775/answers

###
### NEED TO IMPLEMENT THIS NOW
POST http://localhost:3001/questions/62dfdea4c7a4453c21d09775/answers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGZlMTVjZTEyZWE0ZmNlY2U5ZTljMyIsImlhdCI6MTY1ODkwNDY0MSwiZXhwIjoxNjU4OTA4MjQxfQ.zGvF1oIOpNRFFZiZNL2GZec0rLjCeiHcxoDMqcklHUo
Content-Type: application/json

{
    "body": "answer num1",
    "isEdited": false,
    "likes": [],
    "dislikes": [],
    "uid": "62dfe15ce12ea4fcece9e9c3",
    "qid": "62dfdea4c7a4453c21d09775"
}