#CTRL+ALT+R
POST http://localhost:3001/user/register
Content-Type: application/json

{
    "email": "goodbye@email.com",
    "password": "goodbyegoodbye"
}

###

POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email": "hello@email.com",
    "password": "hellohello"
}

###

GET http://localhost:3001/questions

###

POST http://localhost:3001/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGZlMTAxZTEyZWE0ZmNlY2U5ZTljMiIsImlhdCI6MTY1ODg0MTM5MCwiZXhwIjoxNjU4ODQ0OTkwfQ.jqlKXUiKsPKBaXHHZ7mXldOyOK1qmiG5tERGtdlCfJg
Content-Type: application/json

{
    "title": "my title",
    "body": "blahnah",
    "isRead": false,
    "isEdited": false,
    "uid": "62dfe15ce12ea4fcece9e9c3"
}

